// Site copy dictionaries and locale-agnostic string helpers. Kept out of
// i18n.tsx (the provider component file) so Fast Refresh can preserve state.
export type SiteLocale = "en" | "ru";

const en = {
  shared: {
    primaryNavigation: "Primary navigation",
    footerNavigation: "Footer navigation",
    localeControl: "Site language",
    english: "English",
    russian: "Russian",
    switchToLightTheme: "Switch to light theme",
    switchToDarkTheme: "Switch to dark theme",
    githubRepository: "GitHub repository",
    footer: {
      tagline: "Production React UIKit for Telegram Mini Apps.",
      product: "Product",
      community: "Community",
      license: "MIT licensed",
      telegramDemo: "Telegram demo",
      browserDemo: "Browser demo",
      storybook: "Storybook",
      docs: "Docs",
      github: "GitHub",
      npm: "npm",
      issues: "Issues",
      credits: "Built in the open for the Telegram WebView.",
    },
  },
  landing: {
    skipToFeatures: "Skip to features",
    navigation: {
      features: "Features",
      code: "Code",
      getStarted: "Get started",
      demo: "Demo",
    },
    hero: {
      titleBefore: "The iOS-flavored React UI kit for",
      titleAccent: "Telegram Mini Apps",
      titleAfter: "",
      subline: "Zero runtime dependencies · React 18 & 19 · Bot API 9.6",
      installWith: "Install with",
      copyInstall: "Copy install command",
      installCopied: "Install command copied",
      packageFacts: "Package facts",
      openTelegram: "Open demo in Telegram",
      getStarted: "Get started",
      browserDemo: "Browser demo — no Telegram required",
      starGithub: "Star on GitHub",
    },
    wallet: {
      preview: "Static preview of a wallet screen built with tg-mini-app-uikit",
      wallet: "Wallet",
      totalBalance: "Total balance",
      everyday: "Everyday",
      send: "Send",
      add: "Add",
      scan: "Scan",
      activity: "Activity",
      today: "Today",
      subscription: "Subscription",
      transferReceived: "Transfer received",
      sendPayment: "Send payment",
      caption: "Frozen UI · zero timers · built from the same token system",
    },
    features: {
      eyebrow: "Platform foundation",
      title: "Built for the constraints Telegram actually has",
      intro: "Production primitives, platform behavior, and proof in one source package.",
      gesturesTitle: "Native-feel gestures",
      gesturesCopy: "Sheets, galleries, viewers, and edge-aware interactions feel at home in a mobile WebView.",
      telegramTitle: "Telegram out of the box",
      telegramCopy: "Theme mapping, MainButton wrappers, safe areas, and haptics are first-class APIs.",
      motionTitle: "Motion with a budget",
      motionCopy: "Compositor-only animation rules are enforced by CI, with reduced motion built in.",
      accessibilityTitle: "Accessible by default",
      accessibilityCopy: "Keyboard, focus, announcements, names, and touch targets are part of the component contract.",
      dependenciesTitle: "Zero runtime dependencies",
      dependenciesCopy: "The full package stays near 60 kB brotli without shipping a dependency graph to every app.",
      i18nTitle: "Theming and en/ru i18n",
      i18nCopy: "Semantic tokens and bundled English and Russian locales adapt the whole interface at the root.",
    },
    code: {
      eyebrow: "Quickstart",
      title: "From npm to a native-feel screen",
      copy: "Wrap once, compose normal React, and let the kit bridge Telegram behavior without taking over your app architecture.",
      guide: "Read the getting started guide →",
      copyQuickstart: "Copy quickstart code",
      quickstartCopied: "Quickstart code copied",
      quickstartAria: "Typechecked React quickstart",
    },
    getStarted: {
      eyebrow: "Three steps",
      title: "Ship a Mini App in three moves",
      intro: "The shortest path keeps the platform details explicit.",
      install: "Install",
      wrap: "Wrap providers",
      ship: "Ship in Telegram",
      connect: "Connect and validate the platform layer →",
    },
    explore: {
      eyebrow: "Resources",
      title: "Explore the project",
      telegramLabel: "Telegram demo",
      telegramCopy: "Open the native Mini App experience",
      browserLabel: "Browser demo",
      browserCopy: "Try the showcase without Telegram",
      storybookLabel: "Storybook",
      storybookCopy: "Inspect every component and state",
      docsLabel: "Docs",
      docsCopy: "Read guides and API contracts",
      npmLabel: "npm",
      npmCopy: "Install the published package",
      githubLabel: "GitHub",
      githubCopy: "Explore source, issues, and releases",
    },
    copyError: "Could not copy to the clipboard",
  },
  demo: {
    skipToComponents: "Skip to components",
    navigation: {
      features: "Features",
      components: "Components",
      tweaks: "Tweaks",
      i18n: "i18n",
      landing: "Landing",
      context: "Demo",
    },
    notice: {
      action: "Open in Telegram",
      copy: "Browser demo — the kit runs fully without Telegram.",
    },
    hero: {
      title: "iOS-flavored UI kit for Telegram Mini Apps",
      line1: "iOS-flavored UI",
      line2: "kit for Telegram",
      line3: "Mini Apps",
      subline: "Zero runtime dependencies · React 18 & 19 · Bot API 9.6",
      installWith: "Install with",
      copyInstall: "Copy install command",
      installCopied: "Install command copied",
      installCopyError: "Could not copy the install command",
      packageFacts: "Package facts",
      getStarted: "Get started",
      browseComponents: "Browse components",
    },
    wallet: {
      everyday: "Everyday",
      travel: "Travel",
      reserve: "Reserve",
      confirmPayment: "Confirm payment",
      paySecurely: "Pay securely",
      staticHint: "Static preview · reduced motion",
      manualHint: "Manual mode · enter 1234",
      liveHint: "Live wallet flow",
      tryIt: "Try it yourself",
      demoShortcut: "Just a demo shortcut — try the cards, the sheet, and the PIN pad",
      wallet: "Wallet",
      walletOptions: "Wallet options",
      totalBalance: "Total balance",
      payWithCard: "Pay with {card} card ending {digits}",
      shortcuts: "Wallet shortcuts",
      send: "Send",
      add: "Add",
      scan: "Scan",
      activity: "Activity",
      today: "Today",
      subscription: "Subscription",
      transferReceived: "Transfer received",
      backToWallet: "Back to wallet",
      securePayment: "Secure payment",
      paymentComplete: "Payment complete",
      paymentSent: "$4.99 sent securely",
      done: "Done",
    },
    features: {
      title: "Features, proven live",
      intro: "Try the same interaction, theme, performance, and accessibility contracts your Mini App ships.",
      gesturesTitle: "Native-feel gestures",
      gesturesCopy: "Open the sheet, then drag its handle. The UIKit owns the gesture physics, focus trap, and dismissal.",
      telegramTitle: "Telegram out of the box",
      telegramCopy: "Switch token sources. Telegram uses a real injected WebApp mock and the same provider path as production.",
      motionTitle: "Compositor-only motion",
      motionCopy: "The moving layer stays on transform and opacity while React watches the sheet demo next door.",
      accessibilityTitle: "Accessible by default",
      accessibilityCopy: "Tab through real UIKit controls, then run an async action to see exactly what assistive tech hears.",
      tripPlanner: "Trip planner",
      lisbonWeekend: "Weekend in Lisbon",
      viewportCopy: "Everything stays inside this mini viewport.",
      openSheet: "Open draggable sheet",
      itinerary: "Your itinerary",
      dismissSheet: "Drag this header down to dismiss, or press Escape.",
      done: "Done",
      gestureHint: "Pointer or touch to drag · Enter to open · Escape to close",
      themeAria: "Mini app theme",
      light: "Light",
      dark: "Dark",
      telegram: "Telegram",
      lightTokens: "light UIKit tokens",
      darkTokens: "dark UIKit tokens",
      telegramTokens: "Telegram themeParams",
      expenseApproval: "Expense approval",
      teamOffsite: "Team offsite",
      approveExpense: "Approve expense",
      approved: "Approved",
      themeHint: "Use arrow keys inside the segmented control",
      playMotion: "Play motion",
      pauseMotion: "Pause motion",
      commitsTitle: "React commits while pixels move",
      commitsInitial: "Open and drag the sheet to measure.",
      commitsArmed: "Move the sheet to start measuring.",
      commitsMeasuring: "Measuring move-frame commits…",
      commitsZero: "Last drag: zero move-frame commits.",
      commitsResult: "Last drag: {count} move-frame commits.",
      ciLine: "Transform + opacity only · enforced by CI",
      checking: "Checking the accessible flow…",
      checkComplete: "Accessibility check complete.",
      nextStatus: "Run the action — the live-region text appears here (spoken only when a screen reader is on).",
      runAnnouncement: "Run async announcement",
      focusRings: "Focus rings use --tk-ring",
      assistiveTechHears: "What a screen reader would say",
      focusHint: "Press Tab to see the same focus treatment on every control",
    },
    components: {
      title: "Try the kit live",
      intro: "Open a viewer, swipe a gallery, enter codes, and dismiss a sheet. Each tile uses the public API.",
      storybook: "Storybook",
      imageViewerTitle: "ImageViewer",
      imageViewerCopy: "Open a token-built composition, then pinch, double-tap, or swipe it down.",
      pinTitle: "PinInput",
      pinCopy: "The local verifier accepts 1234 and rejects every other four-digit PIN.",
      galleryTitle: "Gallery",
      galleryCopy: "A scroll-snap gallery with touch, trackpad, and keyboard-operable dots.",
      noticeTitle: "NoticeBar marquee",
      noticeCopy: "Overflow starts only while this tile is visible and motion is allowed.",
      chatTitle: "Chat template",
      chatCopy: "Grouped incoming and outgoing messages, including read-state ticks.",
      confettiTitle: "Confetti",
      confettiCopy: "A one-shot canvas burst mounts on demand and removes itself when finished.",
      sheetTitle: "Sheet",
      sheetCopy: "A real draggable sheet kept inside this miniature viewport.",
      calendarTitle: "Calendar",
      calendarCopy: "Tap the start and end dates, or press and drag across the calendar.",
      otpTitle: "OTP",
      otpCopy: "A real one-time-code input with local completion feedback and resend.",
      sliderTitle: "Slider",
      sliderCopy: "Drag the compositor-friendly thumb or use arrows, Page Up, Home, and End.",
      skeletonTitle: "Skeleton group",
      skeletonCopy: "Shimmer stays parked until you explicitly replay it, and pauses off-screen.",
      switchTitle: "Switch + chips",
      switchCopy: "Two selection patterns with native button semantics and visible state.",
      lazyLoading: "Live demo loads as you approach.",
      signal: "Signal",
      orbit: "Orbit",
      current: "Current",
      tokenComposition: "{label} token composition",
      openImage: "Open {label}",
      imageHint: "Open a preview · double-tap to zoom · swipe down to close",
      enterPin: "Enter wallet PIN",
      pinHint: "Hint: 1234",
      pinAccepted: "PIN accepted",
      tryPin: "Try 1234",
      pinIdle: "Four digits, checked locally",
      swipeContinue: "Swipe to continue",
      noticeText: "UIKit 2.4 is ready: accessible controls, Telegram runtime adapters, tuned gesture physics, and no runtime dependencies. Read the migration notes before upgrading.",
      restoreNotice: "Restore notice",
      tickerRunning: "Ticker running in view",
      tickerParked: "Ticker parked",
      support: "UIKit support",
      online: "online",
      chatPreviewReady: "Your Mini App preview is ready.",
      chatThemeQuestion: "Does it follow Telegram themes?",
      chatThemeAnswer: "Yes — switch the page theme above.",
      rewardReady: "Ready for a reward",
      burstRunning: "Burst in progress",
      canvasUnmounted: "Canvas is unmounted",
      canvasMounted: "Canvas mounted",
      fireConfetti: "Fire confetti",
      openSheet: "Open sheet",
      sheetHint: "Drag the handle or press Escape",
      savedView: "Saved view",
      filtersLocal: "Filters stay on this device.",
      selectedRange: "Selected: {start} – {end}",
      selectRangeEnd: "Choose the end date",
      codeAccepted: "Code accepted",
      resetCode: "Reset",
      otpComplete: "OTP complete",
      otpIdle: "Type any four digits",
      intensity: "Intensity",
      intensityAria: "Demo intensity",
      skeletonPreviewTitle: "Project update",
      skeletonPreviewCopy: "The accessibility review is ready.",
      skeletonPreviewMeta: "Updated just now",
      reloadPreview: "Reload preview",
      orders: "Orders",
      product: "Product",
      security: "Security",
      pushNotifications: "Push notifications",
      notificationChannels: "Notification channels",
      channelsEnabled: "{count} channels enabled",
      notificationsPaused: "Notifications paused",
    },
    tweaks: {
      title: "Tune every surface",
      intro: "Adjust the UIKit at its root. Every demo below the provider inherits the same accent, radius, motion speed, and type scale immediately.",
      controls: "Live theme controls",
      saved: "Saved automatically on this device",
      reset: "Reset",
      accent: "Accent",
      custom: "Custom",
      useAccent: "Use {label} accent",
      chooseAccent: "Choose a custom accent color",
      radius: "Radius",
      radiusAria: "Global radius scale",
      motion: "Motion speed",
      motionAria: "Global motion speed",
      fontSize: "Font size",
      fontSizeAria: "Global base font size",
      previewAria: "Live control preview",
      previewTitle: "Local preview",
      previewCopy: "These controls use the same inherited tokens.",
      previewSwitch: "Live preview switch",
      previewActive: "Preview active",
      previewAction: "Preview action",
      telegramBlue: "Telegram blue",
      green: "Green",
      orange: "Orange",
      purple: "Purple",
      red: "Red",
    },
    i18n: {
      title: "Internationalization, live",
      intro: "One global locale now switches both this page and the kit’s built-in enLocale/ruLocale strings.",
      liveLocale: "One locale, everywhere",
      liveCopy: "Change the language here or in the header. The choice is shared across both pages and saved without a reload.",
      localeAria: "Site and kit locale",
      note: "The hero PIN pad, ImageViewer counter, NoticeBar close label, OTP prompt, and every site-owned label follow the same choice.",
      snippetsTitle: "Start with the public API",
      snippetsCopy: "Short teasers from the getting started, theming, and Telegram guides.",
      install: "Install",
      theme: "Theme",
      telegram: "Telegram",
      copySnippet: "Copy {label} snippet",
      snippetTabs: "Code snippet",
      snippetAria: "{label} code snippet",
      snippetCopied: "{label} snippet copied",
      snippetCopyError: "Could not copy the {label} snippet",
    },
  },
} as const;

type StringShape<T> = {
  readonly [Key in keyof T]: T[Key] extends string ? string : StringShape<T[Key]>;
};

export type SiteStrings = StringShape<typeof en>;

const ru: SiteStrings = {
  shared: {
    primaryNavigation: "Основная навигация",
    footerNavigation: "Навигация в подвале",
    localeControl: "Язык сайта",
    english: "Английский",
    russian: "Русский",
    switchToLightTheme: "Включить светлую тему",
    switchToDarkTheme: "Включить тёмную тему",
    githubRepository: "Репозиторий на GitHub",
    footer: {
      tagline: "Продакшен-UIKit на React для Telegram Mini Apps.",
      product: "Продукт",
      community: "Сообщество",
      license: "Лицензия MIT",
      telegramDemo: "Демо в Telegram",
      browserDemo: "Демо в браузере",
      storybook: "Storybook",
      docs: "Документация",
      github: "GitHub",
      npm: "npm",
      issues: "Задачи и ошибки",
      credits: "Создан открыто для Telegram WebView.",
    },
  },
  landing: {
    skipToFeatures: "Перейти к возможностям",
    navigation: {
      features: "Возможности",
      code: "Код",
      getStarted: "Начало работы",
      demo: "Демо",
    },
    hero: {
      titleBefore: "React UIKit в стиле iOS для",
      titleAccent: "мини-приложений Telegram",
      titleAfter: "",
      subline: "Без зависимостей в рантайме · React 18 и 19 · Bot API 9.6",
      installWith: "Установить командой",
      copyInstall: "Скопировать команду установки",
      installCopied: "Команда установки скопирована",
      packageFacts: "О пакете",
      openTelegram: "Открыть демо в Telegram",
      getStarted: "Начать работу",
      browserDemo: "Демо в браузере — Telegram не нужен",
      starGithub: "Поставить звезду на GitHub",
    },
    wallet: {
      preview: "Статичный экран кошелька, собранный на tg-mini-app-uikit",
      wallet: "Кошелёк",
      totalBalance: "Общий баланс",
      everyday: "Основная",
      send: "Перевести",
      add: "Пополнить",
      scan: "Сканировать",
      activity: "Операции",
      today: "Сегодня",
      subscription: "Подписка",
      transferReceived: "Получен перевод",
      sendPayment: "Отправить платёж",
      caption: "Статичный UI · без таймеров · та же система токенов",
    },
    features: {
      eyebrow: "Основа платформы",
      title: "Создан с учётом реальных ограничений Telegram",
      intro: "Компоненты, поведение платформы и доказательства качества — в одном пакете.",
      gesturesTitle: "Жесты как в нативном приложении",
      gesturesCopy: "Шторки, галереи и просмотр изображений естественно работают даже в тесном мобильном WebView.",
      telegramTitle: "Готов к Telegram из коробки",
      telegramCopy: "Темы, обёртки MainButton, safe area и тактильный отклик доступны как полноценные API.",
      motionTitle: "Анимация без лишних затрат",
      motionCopy: "CI следит, чтобы анимации работали силами композитора, а режим reduced motion поддерживается изначально.",
      accessibilityTitle: "Доступность по умолчанию",
      accessibilityCopy: "Клавиатура, фокус, объявления, доступные имена и размеры зон нажатия входят в контракт компонентов.",
      dependenciesTitle: "Без зависимостей в рантайме",
      dependenciesCopy: "Весь пакет занимает около 60 kB brotli и не тащит граф зависимостей в каждое приложение.",
      i18nTitle: "Темы и локализация en/ru",
      i18nCopy: "Семантические токены и встроенные русская и английская локали адаптируют весь интерфейс на уровне корня.",
    },
    code: {
      eyebrow: "Быстрый старт",
      title: "От npm до нативного интерфейса",
      copy: "Один раз подключите провайдеры, пишите обычный React, а UIKit возьмёт на себя интеграцию с Telegram, не диктуя архитектуру приложения.",
      guide: "Открыть руководство по началу работы →",
      copyQuickstart: "Скопировать код быстрого старта",
      quickstartCopied: "Код быстрого старта скопирован",
      quickstartAria: "Проверенный TypeScript-компилятором пример React",
    },
    getStarted: {
      eyebrow: "Три шага",
      title: "Три шага до готового Mini App",
      intro: "Короткий путь, на котором детали платформы остаются явными.",
      install: "Установите",
      wrap: "Подключите провайдеры",
      ship: "Запустите в Telegram",
      connect: "Подключить и проверить платформенный слой →",
    },
    explore: {
      eyebrow: "Ресурсы",
      title: "Изучите проект",
      telegramLabel: "Демо в Telegram",
      telegramCopy: "Откройте Mini App в нативной среде",
      browserLabel: "Демо в браузере",
      browserCopy: "Попробуйте showcase без Telegram",
      storybookLabel: "Storybook",
      storybookCopy: "Изучите каждый компонент и состояние",
      docsLabel: "Документация",
      docsCopy: "Читайте руководства и API-контракты",
      npmLabel: "npm",
      npmCopy: "Установите опубликованный пакет",
      githubLabel: "GitHub",
      githubCopy: "Посмотрите код, задачи и релизы",
    },
    copyError: "Не удалось скопировать в буфер обмена",
  },
  demo: {
    skipToComponents: "Перейти к компонентам",
    navigation: {
      features: "Возможности",
      components: "Компоненты",
      tweaks: "Настройка",
      i18n: "i18n",
      landing: "Главная",
      context: "Демо",
    },
    notice: {
      action: "Открыть в Telegram",
      copy: "Демо в браузере — UIKit полноценно работает и без Telegram.",
    },
    hero: {
      title: "UIKit в стиле iOS для Telegram Mini Apps",
      line1: "UIKit в стиле iOS",
      line2: "для Telegram",
      line3: "Mini Apps",
      subline: "Без зависимостей в рантайме · React 18 и 19 · Bot API 9.6",
      installWith: "Установить командой",
      copyInstall: "Скопировать команду установки",
      installCopied: "Команда установки скопирована",
      installCopyError: "Не удалось скопировать команду установки",
      packageFacts: "О пакете",
      getStarted: "Начать работу",
      browseComponents: "Посмотреть компоненты",
    },
    wallet: {
      everyday: "Основная",
      travel: "Для поездок",
      reserve: "Резерв",
      confirmPayment: "Подтвердите платёж",
      paySecurely: "Безопасная оплата",
      staticHint: "Статичный просмотр · анимация сокращена",
      manualHint: "Ручной режим · введите 1234",
      liveHint: "Сценарий кошелька",
      tryIt: "Попробовать самому",
      demoShortcut: "Это демо-ярлык — попробуйте карты, шторку и пин-пад",
      wallet: "Кошелёк",
      walletOptions: "Настройки кошелька",
      totalBalance: "Общий баланс",
      payWithCard: "Оплатить картой «{card}» с номером •••• {digits}",
      shortcuts: "Быстрые действия кошелька",
      send: "Перевести",
      add: "Пополнить",
      scan: "Сканировать",
      activity: "Операции",
      today: "Сегодня",
      subscription: "Подписка",
      transferReceived: "Получен перевод",
      backToWallet: "Вернуться в кошелёк",
      securePayment: "Безопасный платёж",
      paymentComplete: "Платёж выполнен",
      paymentSent: "Безопасно отправлено: $4.99",
      done: "Готово",
    },
    features: {
      title: "Возможности в действии",
      intro: "Проверьте те же контракты взаимодействия, тем, производительности и доступности, с которыми выйдет ваш Mini App.",
      gesturesTitle: "Жесты как в нативном приложении",
      gesturesCopy: "Откройте шторку и потяните за ручку. UIKit управляет физикой жеста, ловушкой фокуса и закрытием.",
      telegramTitle: "Готов к Telegram из коробки",
      telegramCopy: "Переключайте источники токенов. Режим Telegram использует настоящий мок WebApp и тот же стек провайдеров, что и продакшен.",
      motionTitle: "Анимация силами композитора",
      motionCopy: "Движущийся слой меняет только transform и opacity, пока React отслеживает соседнюю шторку.",
      accessibilityTitle: "Доступность по умолчанию",
      accessibilityCopy: "Пройдите по компонентам с клавиатуры, затем запустите действие и узнайте, что услышат пользователи скринридера.",
      tripPlanner: "План поездки",
      lisbonWeekend: "Выходные в Лиссабоне",
      viewportCopy: "Весь сценарий остаётся внутри этого мини-экрана.",
      openSheet: "Открыть шторку",
      itinerary: "Ваш маршрут",
      dismissSheet: "Потяните заголовок вниз или нажмите Escape.",
      done: "Готово",
      gestureHint: "Тяните мышью или пальцем · Enter — открыть · Escape — закрыть",
      themeAria: "Тема Mini App",
      light: "Светлая",
      dark: "Тёмная",
      telegram: "Telegram",
      lightTokens: "светлые токены UIKit",
      darkTokens: "тёмные токены UIKit",
      telegramTokens: "Telegram themeParams",
      expenseApproval: "Согласование расходов",
      teamOffsite: "Командная встреча",
      approveExpense: "Согласовать расход",
      approved: "Согласовано",
      themeHint: "Переключайте варианты стрелками на клавиатуре",
      playMotion: "Запустить анимацию",
      pauseMotion: "Остановить анимацию",
      commitsTitle: "Коммиты React во время движения",
      commitsInitial: "Откройте шторку и потяните её, чтобы измерить.",
      commitsArmed: "Сдвиньте шторку, чтобы начать измерение.",
      commitsMeasuring: "Считаем коммиты во время движения…",
      commitsZero: "Последний жест: ни одного коммита во время движения.",
      commitsResult: "Последний жест: коммитов во время движения — {count}.",
      ciLine: "Только transform + opacity · проверяется в CI",
      checking: "Проверяем доступный сценарий…",
      checkComplete: "Проверка доступности завершена.",
      nextStatus: "Запустите действие — здесь появится текст live-региона (звучит только при включённом скринридере).",
      runAnnouncement: "Запустить асинхронное объявление",
      focusRings: "Фокус использует --tk-ring",
      assistiveTechHears: "Что произнесёт скринридер",
      focusHint: "Нажимайте Tab — оформление фокуса одинаково на всех элементах",
    },
    components: {
      title: "Попробуйте UIKit сами",
      intro: "Откройте ImageViewer, пролистайте галерею, введите коды и закройте шторку. Каждая плитка использует публичный API.",
      storybook: "Storybook",
      imageViewerTitle: "ImageViewer",
      imageViewerCopy: "Откройте композицию на токенах, увеличьте щипком или двойным нажатием либо смахните вниз.",
      pinTitle: "PinInput",
      pinCopy: "Локальная проверка принимает 1234 и отклоняет любой другой четырёхзначный PIN.",
      galleryTitle: "Gallery",
      galleryCopy: "Галерея со scroll snap, управлением касанием, трекпадом и доступными с клавиатуры точками.",
      noticeTitle: "Бегущая строка NoticeBar",
      noticeCopy: "Текст движется, только пока плитка видна и пользователь не сократил анимации.",
      chatTitle: "Шаблон чата",
      chatCopy: "Сгруппированные входящие и исходящие сообщения с отметками о прочтении.",
      confettiTitle: "Confetti",
      confettiCopy: "Canvas появляется для одного залпа и удаляется сразу после завершения.",
      sheetTitle: "Sheet",
      sheetCopy: "Настоящая перетаскиваемая шторка внутри миниатюрного экрана.",
      calendarTitle: "Calendar",
      calendarCopy: "Коснитесь дат начала и конца или нажмите и протяните по календарю.",
      otpTitle: "OTP",
      otpCopy: "Настоящий ввод одноразового кода с локальной проверкой и повторной отправкой.",
      sliderTitle: "Slider",
      sliderCopy: "Двигайте бегунок без лишних перерисовок или используйте стрелки, Page Up, Home и End.",
      skeletonTitle: "Группа скелетонов",
      skeletonCopy: "Мерцающая загрузка запускается только по команде и останавливается за пределами экрана.",
      switchTitle: "Switch + chips",
      switchCopy: "Два паттерна выбора с нативной семантикой кнопок и наглядным состоянием.",
      lazyLoading: "Живое демо загрузится, когда вы приблизитесь.",
      signal: "Сигнал",
      orbit: "Орбита",
      current: "Поток",
      tokenComposition: "Композиция из токенов «{label}»",
      openImage: "Открыть «{label}»",
      imageHint: "Откройте превью · двойное нажатие — увеличить · смахните вниз — закрыть",
      enterPin: "Введите PIN кошелька",
      pinHint: "Подсказка: 1234",
      pinAccepted: "PIN принят",
      tryPin: "Попробуйте 1234",
      pinIdle: "Четыре цифры, локальная проверка",
      swipeContinue: "Листайте дальше",
      noticeText: "UIKit 2.4 готов: доступные элементы управления, адаптеры Telegram WebApp, точная физика жестов и никаких зависимостей в рантайме. Перед обновлением прочитайте руководство по миграции.",
      restoreNotice: "Вернуть уведомление",
      tickerRunning: "Строка движется в области просмотра",
      tickerParked: "Строка остановлена",
      support: "Поддержка UIKit",
      online: "в сети",
      chatPreviewReady: "Превью вашего Mini App готово.",
      chatThemeQuestion: "Оно следует теме Telegram?",
      chatThemeAnswer: "Да — переключите тему страницы выше.",
      rewardReady: "Всё готово к награде",
      burstRunning: "Залп уже идёт",
      canvasUnmounted: "Canvas не смонтирован",
      canvasMounted: "Canvas смонтирован",
      fireConfetti: "Запустить конфетти",
      openSheet: "Открыть шторку",
      sheetHint: "Потяните за ручку или нажмите Escape",
      savedView: "Сохранённый вид",
      filtersLocal: "Фильтры хранятся на этом устройстве.",
      selectedRange: "Выбрано: {start} — {end}",
      selectRangeEnd: "Выберите дату окончания",
      codeAccepted: "Код принят",
      resetCode: "Сбросить",
      otpComplete: "Код введён полностью",
      otpIdle: "Введите любые четыре цифры",
      intensity: "Интенсивность",
      intensityAria: "Интенсивность демо",
      skeletonPreviewTitle: "Обновление проекта",
      skeletonPreviewCopy: "Проверка доступности готова.",
      skeletonPreviewMeta: "Обновлено только что",
      reloadPreview: "Перезапустить превью",
      orders: "Заказы",
      product: "Продукт",
      security: "Безопасность",
      pushNotifications: "Push-уведомления",
      notificationChannels: "Каналы уведомлений",
      channelsEnabled: "Включено каналов: {count}",
      notificationsPaused: "Уведомления приостановлены",
    },
    tweaks: {
      title: "Настройте каждый экран",
      intro: "Меняйте UIKit на уровне корня. Все демо внутри провайдера сразу наследуют акцент, скругление, скорость анимаций и масштаб текста.",
      controls: "Настройки темы в реальном времени",
      saved: "Автоматически сохраняются на устройстве",
      reset: "Сбросить",
      accent: "Акцент",
      custom: "Свой цвет",
      useAccent: "Выбрать акцент «{label}»",
      chooseAccent: "Выбрать собственный цвет акцента",
      radius: "Скругление",
      radiusAria: "Общий масштаб скруглений",
      motion: "Скорость анимаций",
      motionAria: "Общая скорость анимаций",
      fontSize: "Размер шрифта",
      fontSizeAria: "Базовый размер шрифта",
      previewAria: "Превью элементов управления",
      previewTitle: "Локальное превью",
      previewCopy: "Эти элементы используют те же унаследованные токены.",
      previewSwitch: "Переключатель живого превью",
      previewActive: "Превью активно",
      previewAction: "Действие в превью",
      telegramBlue: "Синий Telegram",
      green: "Зелёный",
      orange: "Оранжевый",
      purple: "Фиолетовый",
      red: "Красный",
    },
    i18n: {
      title: "Локализация в действии",
      intro: "Одна глобальная локаль одновременно переключает текст страницы и встроенные строки UIKit из enLocale/ruLocale.",
      liveLocale: "Одна локаль для всего",
      liveCopy: "Меняйте язык здесь или в шапке. Выбор общий для обеих страниц, сохраняется и не требует перезагрузки.",
      localeAria: "Локаль сайта и UIKit",
      note: "PIN-клавиатура на первом экране, счётчик ImageViewer, кнопка закрытия NoticeBar, OTP-подсказка и весь текст сайта следуют одному выбору.",
      snippetsTitle: "Начните с публичного API",
      snippetsCopy: "Короткие фрагменты из руководств по началу работы, темам и интеграции с Telegram.",
      install: "Установка",
      theme: "Тема",
      telegram: "Telegram",
      copySnippet: "Скопировать сниппет «{label}»",
      snippetTabs: "Сниппет кода",
      snippetAria: "Сниппет кода «{label}»",
      snippetCopied: "Сниппет «{label}» скопирован",
      snippetCopyError: "Не удалось скопировать сниппет «{label}»",
    },
  },
};

export const STRINGS = { en, ru } as const satisfies Record<SiteLocale, SiteStrings>;
export const SITE_LOCALE_STORAGE_KEY = "showcase-locale";

export function formatSiteString(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (message, [key, value]) => message.split(`{${key}}`).join(String(value)),
    template,
  );
}
